[package]
name = "withd"
authors = ["Gavin Panella <gavin@allenap.me>"]
description = "Run a command in another directory."
license-file = "LICENSE"
repository = "https://github.com/allenap/withd"
readme = "README.md"
keywords = ["cd", "cdpath"]
categories = ["command-line-utilities"]
version = "0.3.1"
edition = "2021"

[[bin]]
name = "withd"
doc = false

[[bin]]
name = "completions"
path = "src/completions.rs"
doc = false

[dependencies]
bstr = "=1.9.1"
clap = { version = "=4.5.6", features = ["derive", "env", "wrap_help"] }
clap_complete = "=4.5.5"
lazy-regex = "=3.1.0"
tempfile = "=3.10.1"
thiserror = "=1.0.61"

[target.'cfg(unix)'.dependencies]
nix = { version = "=0.29.0", features = ["signal"], default-features = false }
