[package]
name = "withd"
authors = ["Gavin Panella <gavin@allenap.me>"]
description = "Run a command in another directory."
license-file = "LICENSE"
repository = "https://github.com/allenap/withd"
readme = "README.md"
keywords = ["cd", "cdpath"]
categories = ["command-line-utilities"]
version = "0.2.2"
edition = "2021"

[dependencies]
bstr = "=1.9.1"
clap = { version = "=4.5.4", features = ["derive"] }
lazy-regex = "=3.1.0"
tempfile = "=3.10.1"
thiserror = "=1.0.61"

[target.'cfg(unix)'.dependencies]
nix = { version = "=0.29.0", features = ["signal"], default-features = false }

[workspace.metadata.cross.target.x86_64-unknown-linux-musl]
# Install musl-tools:arm64, see
# <https://github.com/cross-rs/cross/blob/main/docs/custom_images.md#adding-dependencies-to-existing-images>
pre-build = [
    "dpkg --add-architecture amd64",
    "apt-get update && apt-get --assume-yes install musl-tools:amd64",
]

[workspace.metadata.cross.target.aarch64-unknown-linux-musl]
# Install musl-tools:arm64, see
# <https://github.com/cross-rs/cross/blob/main/docs/custom_images.md#adding-dependencies-to-existing-images>
pre-build = [
    "dpkg --add-architecture arm64",
    "apt-get update && apt-get --assume-yes install musl-tools:arm64",
]
