[package]
name = "withd"
authors = ["Gavin Panella <gavin@allenap.me>"]
description = "Run a command in another directory."
license-file = "LICENSE"
repository = "https://github.com/allenap/withd"
readme = "README.md"
keywords = ["cd", "cdpath"]
categories = ["command-line-utilities"]
version = "0.1.0"
edition = "2021"

[dependencies]
bstr = "=1.9.1"
clap = { version = "=4.5.4", features = ["derive"] }
tempfile = "=3.10.1"
