name: withd Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  apple-darwin-aarch64-binary:
    name: Build macOS ARM
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --release --target aarch64-apple-darwin
      - name: Smoke test
        run: target/aarch64-apple-darwin/release/withd --help
      - uses: actions/upload-artifact@v4
        with:
          name: aarch64-apple-darwin
          path: target/aarch64-apple-darwin/release/withd
          if-no-files-found: error

  apple-darwin-x86_64-binary:
    name: Build macOS Intel
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-apple-darwin
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --release --target x86_64-apple-darwin
      - name: Smoke test
        run: target/x86_64-apple-darwin/release/withd --help
      - uses: actions/upload-artifact@v4
        with:
          name: x86_64-apple-darwin
          path: target/x86_64-apple-darwin/release/withd
          if-no-files-found: error

  apple-darwin-universal-binary:
    name: Build macOS Universal
    runs-on: macos-latest
    needs: [apple-darwin-aarch64-binary, apple-darwin-x86_64-binary]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: x86_64-apple-darwin
          path: withd-x86_64-apple-darwin
      - uses: actions/download-artifact@v4
        with:
          name: aarch64-apple-darwin
          path: withd-aarch64-apple-darwin
      - name: debug
        run: find .
      - name: Build Universal macOS binary
        run: |
          lipo -create \
            -output withd-apple-darwin \
            withd-x86_64-apple-darwin/withd \
            withd-aarch64-apple-darwin/withd
      - name: Smoke test
        run: |
          find .
          ls -lR
          chmod 0755 ./withd-apple-darwin
          ./withd-apple-darwin --help
      - uses: actions/upload-artifact@v4
        with:
          name: apple-darwin
          path: withd-apple-darwin
          if-no-files-found: error

  linux-aarch64-binary:
    name: Build Linux ARM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "v0-cross-aarch64"
      - name: Install `cross-rs/cross` for cross-compilation of Rust
        run: cargo install cross --git https://github.com/cross-rs/cross
      - name: Build aarch64
        run: cross build --release --target aarch64-unknown-linux-musl
      - name: Smoke test
        run: cross run --release --target aarch64-unknown-linux-musl --bin withd -- --help
      - uses: actions/upload-artifact@v4
        with:
          name: aarch64-linux
          path: target/aarch64-unknown-linux-musl/release/withd
          if-no-files-found: error

  linux-x86_64-binary:
    name: Build Linux Intel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "v0-cross-x86_64"
      - name: Install `cross-rs/cross` for cross-compilation of Rust
        run: cargo install cross --git https://github.com/cross-rs/cross
      - name: Build x86_64
        run: cross build --release --target x86_64-unknown-linux-musl
      - name: Smoke test
        run: cross run  --release --target x86_64-unknown-linux-musl --bin withd -- --help
      - uses: actions/upload-artifact@v4
        with:
          name: x86_64-linux
          path: target/x86_64-unknown-linux-musl/release/withd
          if-no-files-found: error

  release:
    name: Create release
    permissions:
      contents: write
    needs:
      - apple-darwin-aarch64-binary
      - apple-darwin-x86_64-binary
      - apple-darwin-universal-binary
      - linux-aarch64-binary
      - linux-x86_64-binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: "*-linux"
          path: linux
      - uses: actions/download-artifact@v4
        with:
          pattern: "*-apple-darwin"
          path: apple-darwin
      - uses: actions/download-artifact@v4
        with:
          name: apple-darwin
      - name: Rename executables
        run: |
          find apple-darwin linux -ls
          mv -v apple-darwin/aarch64-apple-darwin/withd withd-apple-darwin-aarch64
          mv -v apple-darwin/x86_64-apple-darwin/withd withd-apple-darwin-x86_64
          mv -v linux/aarch64-linux/withd withd-linux-aarch64
          mv -v linux/x86_64-linux/withd withd-linux-x86_64
      - uses: actions/upload-artifact@v4
        with:
          name: release
          path: withd-*
          if-no-files-found: error
          overwrite: true
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            withd-apple-darwin-aarch64
            withd-apple-darwin-x86_64
            withd-apple-darwin
            withd-linux-aarch64
            withd-linux-x86_64
          fail_on_unmatched_files: true
        if: startsWith(github.ref, 'refs/tags/')
