name: withd Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to make into a release"
        required: true
        default: "v0.0.0"
        type: string
  push:
    tags:
      - "v*"

jobs:
  aarch64-apple-darwin-release:
    name: Build macOS ARM
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --release --target aarch64-apple-darwin
      - name: Smoke test
        run: target/aarch64-apple-darwin/release/withd --help
      - uses: actions/upload-artifact@v4
        with:
          name: aarch64-apple-darwin
          path: target/aarch64-apple-darwin/release/withd
          if-no-files-found: error

  x86_64-apple-darwin-release:
    name: Build macOS Intel
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-apple-darwin
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --release --target x86_64-apple-darwin
      - name: Smoke test
        run: target/x86_64-apple-darwin/release/withd --help
      - uses: actions/upload-artifact@v4
        with:
          name: x86_64-apple-darwin
          path: target/x86_64-apple-darwin/release/withd
          if-no-files-found: error

  macos-universal-release:
    name: Build macOS Universal
    runs-on: macos-latest
    needs: [aarch64-apple-darwin-release, x86_64-apple-darwin-release]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: x86_64-apple-darwin
          path: withd-x86_64-apple-darwin
      - uses: actions/download-artifact@v4
        with:
          name: aarch64-apple-darwin
          path: withd-aarch64-apple-darwin
      - name: debug
        run: find .
      - name: Build Universal macOS Binary
        run: |
          lipo -create \
            -output withd-apple-darwin \
            withd-x86_64-apple-darwin/withd \
            withd-aarch64-apple-darwin/withd
      - name: Smoke test
        run: |
          find .
          ls -lR
          chmod 0755 ./withd-apple-darwin
          ./withd-apple-darwin --help
      - uses: actions/upload-artifact@v4
        with:
          name: apple-darwin
          path: withd-apple-darwin
          if-no-files-found: error

  linux-release:
    name: Build Linux
    runs-on: ubuntu-22.04
    steps:
      - name: Install dev tools
        run: |
          sudo apt update
          sudo apt -y install musl-tools libssl-dev
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-musl
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --release --target x86_64-unknown-linux-musl
      - name: Smoke test
        run: target/x86_64-unknown-linux-musl/release/withd --help
      - uses: actions/upload-artifact@v4
        with:
          name: linux
          path: target/x86_64-unknown-linux-musl/release/withd
          if-no-files-found: error

  create-release:
    name: Create release
    needs: [macos-universal-release, linux-release]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: linux
          path: linux
      - uses: actions/download-artifact@v4
        with:
          name: apple-darwin
      - name: Rename executables
        run: |
          mv -v linux/withd withd-linux
          find .
      - uses: softprops/action-gh-release@v2
        with:
          name: ${{ inputs.version || github.ref }}
          tag_name: ${{ inputs.version || github.ref }}
          files: |
            withd-apple-darwin
            withd-linux
          fail_on_unmatched_files: true
