name: withd Release

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Ref to build (and release, if it's a tag)"
        required: true
        default: "refs/tags/v0.2.2"
        type: string
  push:
    tags:
      - "v*"

jobs:
  aarch64-apple-darwin-release:
    name: Build macOS ARM
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.ref }}
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --release --target aarch64-apple-darwin
      - name: Smoke test
        run: target/aarch64-apple-darwin/release/withd --help
      - uses: actions/upload-artifact@v4
        with:
          name: aarch64-apple-darwin
          path: target/aarch64-apple-darwin/release/withd
          if-no-files-found: error

  x86_64-apple-darwin-release:
    name: Build macOS Intel
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.ref }}
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-apple-darwin
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --release --target x86_64-apple-darwin
      - name: Smoke test
        run: target/x86_64-apple-darwin/release/withd --help
      - uses: actions/upload-artifact@v4
        with:
          name: x86_64-apple-darwin
          path: target/x86_64-apple-darwin/release/withd
          if-no-files-found: error

  macos-universal-release:
    name: Build macOS Universal
    runs-on: macos-latest
    needs: [aarch64-apple-darwin-release, x86_64-apple-darwin-release]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: x86_64-apple-darwin
          path: withd-x86_64-apple-darwin
      - uses: actions/download-artifact@v4
        with:
          name: aarch64-apple-darwin
          path: withd-aarch64-apple-darwin
      - name: debug
        run: find .
      - name: Build Universal macOS Binary
        run: |
          lipo -create \
            -output withd-apple-darwin \
            withd-x86_64-apple-darwin/withd \
            withd-aarch64-apple-darwin/withd
      - name: Smoke test
        run: |
          find .
          ls -lR
          chmod 0755 ./withd-apple-darwin
          ./withd-apple-darwin --help
      - uses: actions/upload-artifact@v4
        with:
          name: apple-darwin
          path: withd-apple-darwin
          if-no-files-found: error

  linux-release:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.ref }}
      - uses: dtolnay/rust-toolchain@stable
      - name: Install `cross-rs/cross` for cross-compilation of Rust
        run: cargo install cross --git https://github.com/cross-rs/cross
      # Build & upload x86_64.
      - name: Build x86_64
        run: cross build --release --target x86_64-unknown-linux-musl
      - name: Smoke test x86_64
        run: target/x86_64-unknown-linux-musl/release/withd --help
      - uses: actions/upload-artifact@v4
        with:
          name: x86_64-linux
          path: target/x86_64-unknown-linux-musl/release/withd
          if-no-files-found: error
      # Build & upload aarch64.
      - name: Build aarch64
        run: cross build --release --target aarch64-unknown-linux-musl
      - name: Smoke test aarch64
        run: target/aarch64-unknown-linux-musl/release/withd --help
      - uses: actions/upload-artifact@v4
        with:
          name: aarch64-linux
          path: target/aarch64-unknown-linux-musl/release/withd
          if-no-files-found: error

  create-release:
    name: Create release
    needs: [macos-universal-release, linux-release]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: "*-linux"
          merge-multiple: true
          path: linux
      - uses: actions/download-artifact@v4
        with:
          pattern: "*-apple-darwin"
          merge-multiple: true
          path: apple-darwin
      - uses: actions/download-artifact@v4
        with:
          name: apple-darwin
      - name: Rename executables
        run: |
          find apple-darwin linux -ls
          mv -v linux/x86_64-linux/withd withd-linux-x86_64
          mv -v linux/aarch64-linux/withd withd-linux-aarch64
          mv -v apple-darwin/x86_64-linux/withd withd-linux-x86_64
          mv -v apple/darwin/aarch64-linux/withd withd-linux-aarch64
      - uses: actions/upload-artifact@v4
        with:
          pattern: withd-*
          path: release
          if-no-files-found: error
      - uses: softprops/action-gh-release@v2
        with:
          name: ${{ inputs.ref || github.ref }}
          tag_name: ${{ inputs.ref || github.ref }}
          files: |
            withd-apple-darwin
            withd-linux
          fail_on_unmatched_files: true
        if: startsWith(inputs.ref || github.ref, 'refs/tags/')
